
services:
  postgres:
    image: postgres:17
    container_name: management_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: makhkets
      POSTGRES_PASSWORD: makhkets
      POSTGRES_DB: management
      PGDATA: /var/lib/postgresql/data
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U makhkets -d management"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - management_network

volumes:
  postgres_data:
    driver: local

networks:
  management_network:
    driver: bridge

